name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install libmysqlclient-dev, libssl-dev and openssl
      run: sudo apt-get install -y libmysqlclient-dev libssl-dev openssl
    - name: make
      run: make clean all

